language: node_js
sudo: false
node_js:
  - "6.9.2"
before_install:
  - npm install -g npm
install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
  - $CXX --version
  - npm install
before_script:
  - npm install
script: make test
notifications:
  email: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
